version: 2
pipelines:
- pipeline: "Master build"
  ref: "master"
  stages:
  - stage: "Deployment - production"
    tasks:
    - task: tugboat
      steps:
      - step: "Deploy using Tugboat"
        action: "gcr.io/action-containers/tugboat:1.2.6-1"
        args: ["--user", "jenkins", "installations", "create", "service"]
