# Endpoint used: https://backstage-proxy.spotify.net/api/alchemist 
 
--- 
version: "2" 
beta: false 
useBuildIdentity: false 
timeout: 30 
pipelines: 
- pipeline: "Master build" 
  ref: "master" 
  stages: 
  - stage: "Deployment - production" 
    tasks: 
    - task: "tugboat" 
      steps:
      - id: 'Deploy application to cluster'
        name: 'gcr.io/k8s-skaffold/skaffold:v2.2.0'
        entrypoint: 'bash'
        args:
        - '-c'
        - >
          skaffold run -f=skaffold.yaml --default-repo=gcr.io/$PROJECT_ID;