---
# grpcurl
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcurl
spec:
  selector:
    matchLabels:
      app: grpcurl
  template:
    metadata:
      labels:
        app: grpcurl
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
        sidecar.istio.io/proxyCPU: "500m"
        sidecar.istio.io/proxyMemory: "256Mi"
    spec:
      serviceAccountName: default
      imagePullSecrets:
      - name: gcr-json-key
      containers:
        - name: grpcurl-server
          image: gcr.io/master-thesis-hpa/fullstorydev/grpcurl:latest
          ports:
          - containerPort: 8080
          command:
          - /bin/sh
          - -c 
          - |
            grpcurl -help
          readinessProbe:
            exec:
              command: ["sh", "-c", "grpcurl productcatalogservice:3550 list"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["sh", "-c", "grpcurl productcatalogservice:3550 list"]
            initialDelaySeconds: 10
            periodSeconds: 15
          env:
          - name: PORT
            value: "8080"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice:3550"
          - name: CURRENCY_SERVICE_ADDR
            value: "currencyservice:7000"
          - name: CART_SERVICE_ADDR
            value: "cartservice:7070"
          - name: RECOMMENDATION_SERVICE_ADDR
            value: "recommendationservice:8080"
          - name: SHIPPING_SERVICE_ADDR
            value: "shippingservice:50051"
          - name: CHECKOUT_SERVICE_ADDR
            value: "checkoutservice:5050"
          - name: AD_SERVICE_ADDR
            value: "adservice:9555"
          resources:
            requests:
              cpu: 300m
              memory: 64Mi
            limits:
              cpu: 400m
              memory: 128Mi
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: grpcurl
# spec:
#   type: ClusterIP
#   selector:
#     app: grpcurl
#   ports:
#   - name: http
#     port: 80
#     targetPort: 8080
# ---