# Deploy the RL agent with a Python script manually changing replicas
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  namespace: rl-agent
spec:
  selector:
    matchLabels:
      app: agent
  replicas: 1
  template:
    metadata:
      labels:
        app: agent
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      imagePullSecrets:
      - name: gcr-json-key
      initContainers:
      - name: prometheus-check
        image: curlimages/curl:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "Checking Prometheus API..."
          if ! curl -sf http://prometheus.istio-system.svc.cluster.local:9090; then
            echo "Error: Could not reach Prometheus API"
            exit 1
          fi
      containers:
      - name: server
        image: gcr.io/master-thesis-hpa/agent:0.3.1
        volumeMounts:
          - name: file-storage
            mountPath: /app
        readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
        resources:
          requests:
            cpu: 1000m
            memory: 1024Mi
          limits:
            cpu: 1500m
            memory: 2048Mi
      volumes:
        - name: file-storage
          persistentVolumeClaim:
            claimName: nfs-server-claim