apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-server
spec:
  capacity:
    storage: 1T
  accessModes:
    - ReadWriteMany
  nfs:
    path: /vol1 # path to the shared folder in the server
    server: 10.167.184.82