apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agent-role-binding
  namespace: rl-agent
subjects:
- kind: ServiceAccount
  name: default
  namespace: rl-agent
roleRef:
  kind: Role
  name: agent-role
  apiGroup: rbac.authorization.k8s.io
