apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: nfs-server-claim
 namespace: rl-agent
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""