{
 "title": "Frontend",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(kube_pod_info{pod=~\"frontend-.*\", namespace=\"rl-agent\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(kube_pod_info{pod=~\"frontend-.*\", namespace=\"default\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success measure HPA vs agent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "clamp_max(\n        max(\n            rate(\n                istio_request_duration_milliseconds_count{\n                    pod=~\"frontend-.*\", \n                    request_protocol=\"grpc\", \n                    response_code=\"200\", \n                    namespace=\"rl-agent\"\n                }[1m]\n            )\n        ) < 100, 1\n) * \n(count(kube_pod_info{pod=~\"frontend-.*\", namespace=\"rl-agent\"}))",
     "legendFormat": "rl-agent"
    },
    {
     "expr": "clamp_max(\n        max(\n            rate(\n                istio_request_duration_milliseconds_count{\n                    pod=~\"frontend-.*\", \n                    request_protocol=\"grpc\", \n                    response_code=\"200\", \n                    namespace=\"default\"\n                }[1m]\n            )\n        ) < 100, 1\n) * \n(count(kube_pod_info{pod=~\"frontend-.*\", namespace=\"default\"}))",
     "legendFormat": "default HPA"
    }
   ]
  },
  {
   "title": "Max response time gRPC 200 [ms]",
   "type": "timeseries",
   "description": "Response time of slowest service",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max(rate(istio_request_duration_milliseconds_count{pod=~\"frontend-.*\", request_protocol=\"grpc\", response_code=\"200\", namespace=\"rl-agent\"}[1m]))",
     "legendFormat": "rl-agent"
    },
    {
     "expr": "max(rate(istio_request_duration_milliseconds_count{pod=~\"frontend-.*\", request_protocol=\"grpc\", response_code=\"200\", namespace=\"default\"}[1m]))",
     "legendFormat": "default"
    }
   ]
  },
  {
   "title": "CPU utilisation [%]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{pod=~\"frontend-.*\", namespace=\"default\"}[1m])/0.1*100)",
     "legendFormat": "Avg CPU default"
    },
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{pod=~\"frontend-.*\", namespace=\"rl-agent\"}[1m])/0.1*100)",
     "legendFormat": "Avg CPU rl-agent"
    }
   ]
  },
  {
   "title": "Loadgenerator requests generated per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(istio_requests_total{namespace=\"rl-agent\", source_app=\"loadgenerator\", destination_app=\"frontend\", pod=~\"loadgenerator-.*\", request_protocol=\"http\"}[1m])",
     "legendFormat": "{{namespace}}: {{source_app}} to {{destination_app}}, {{response_code}}"
    },
    {
     "expr": "rate(istio_requests_total{namespace=\"default\", source_app=\"loadgenerator\", destination_app=\"frontend\", pod=~\"loadgenerator-.*\", request_protocol=\"http\"}[1m])",
     "legendFormat": "{{namespace}}: {{source_app}} to {{destination_app}}, {{response_code}}"
    }
   ]
  },
  {
   "title": "Memory usage [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "avg(rate(container_memory_usage_bytes{pod=~\"frontend-.*\", namespace=\"rl-agent\"}[1m])/64000000)",
     "legendFormat": "Avg memory rl-agent"
    },
    {
     "expr": "avg(rate(container_memory_usage_bytes{pod=~\"frontend-.*\", namespace=\"default\"}[1m])/64000000)",
     "legendFormat": "Avg memory default"
    }
   ]
  }
 ]
}