{
 "title": "Experiment 1 - Testing paymentservice",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "RPS to the pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(sum by (pod) (rate(istio_requests_total{reporter=\"destination\", namespace=\"default\", destination_workload=\"productcatalogservice\"}[1m])))",
     "legendFormat": "default, avg per pod"
    },
    {
     "expr": "((rate(istio_requests_total{reporter=\"destination\", namespace=\"default\", destination_workload=\"productcatalogservice\"}[1m])))",
     "legendFormat": "default, total"
    }
   ]
  },
  {
   "title": "CPU utilisation [%]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "(sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"product.*\", image!=\"\"}[2m])) /\nsum by (pod) (kube_pod_container_resource_requests{namespace=\"default\", unit=\"core\", pod=~\"product.*\"}) * 100)",
     "legendFormat": "Average pod, default"
    }
   ]
  },
  {
   "title": "Memory usage [%]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "(sum by (pod) (rate(container_memory_usage_bytes{namespace=\"default\", pod=~\"product.*\", image!=\"\"}[2m])) /\nsum by (pod) (kube_pod_container_resource_requests{namespace=\"default\", unit=\"byte\", pod=~\"product.*\"}) * 100)"
    }
   ]
  },
  {
   "title": "p95 latency of the pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "((histogram_quantile(\n      0.95,\n      sum by (le) (\n        rate(\n          istio_request_duration_milliseconds_bucket{\n            reporter=\"destination\",\n            destination_service_namespace=\"testing\",\n            response_code=\"200\",\n            pod=~\"productcatalogservice-.*\"\n          }[1m]\n        )\n      )\n    )\n))",
     "legendFormat": "testing"
    },
    {
     "expr": "((histogram_quantile(\n      0.95,\n      sum by (le) (\n        rate(\n          istio_request_duration_milliseconds_bucket{\n            reporter=\"destination\",\n            destination_service_namespace=\"default\",\n            response_code=\"200\",\n            pod=~\"productcatalogservice-.*\"\n          }[1m]\n        )\n      )\n    )\n))",
     "legendFormat": "default"
    }
   ]
  },
  {
   "title": "All timeseries together",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg(sum by (pod) (rate(istio_requests_total{reporter=\"destination\", namespace=\"testing\", destination_workload=\"productcatalogservice\"}[1m])))",
     "legendFormat": "RPS-testing"
    },
    {
     "expr": "avg(sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"testing\", pod=~\"product.*\", image!=\"\"}[2m])) /\nsum by (pod) (kube_pod_container_resource_requests{namespace=\"testing\", unit=\"core\", pod=~\"product.*\"}) * 100)",
     "legendFormat": "CPU-testing"
    },
    {
     "expr": "((histogram_quantile(\n      0.95,\n      sum by (le) (\n        rate(\n          istio_request_duration_milliseconds_bucket{\n            reporter=\"destination\",\n            destination_service_namespace=\"testing\",\n            response_code=\"200\",\n            pod=~\"productcatalogservice-.*\"\n          }[1m]\n        )\n      )\n    )\n))",
     "legendFormat": "p95-testing"
    },
    {
     "expr": "count(kube_pod_info{pod=~\"productcatalogservice-.*\", namespace=\"testing\"})",
     "legendFormat": "replicas-testing"
    },
    {
     "expr": "avg(sum by (pod) (rate(istio_requests_total{reporter=\"destination\", namespace=\"rl-agent-e1-a2c\", destination_workload=\"productcatalogservice\"}[1m])))",
     "legendFormat": "RPS-rl-agent-e1-a2c"
    },
    {
     "expr": "avg(sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"rl-agent-e1-a2c\", pod=~\"product.*\", image!=\"\"}[2m])) /\nsum by (pod) (kube_pod_container_resource_requests{namespace=\"rl-agent-e1-a2c\", unit=\"core\", pod=~\"product.*\"}) * 100)",
     "legendFormat": "CPU-rl-agent-e1-a2c"
    },
    {
     "expr": "(histogram_quantile(\n      0.95,\n      sum by (le) (\n        rate(\n          istio_request_duration_milliseconds_bucket{\n            reporter=\"destination\",\n            destination_service_namespace=\"rl-agent-e1-a2c\",\n            response_code=\"200\",\n            pod=~\"productcatalogservice-.*\"\n          }[1m]\n        )\n      )\n    )\n  )",
     "legendFormat": "p95-rl-agent-e1-a2c"
    },
    {
     "expr": "count(kube_pod_info{pod=~\"productcatalogservice-.*\", namespace=\"rl-agent-e1-a2c\"})",
     "legendFormat": "replicas-rl-agent-e1-a2c"
    },
    {
     "expr": "avg(sum by (pod) (rate(container_memory_usage_bytes{namespace=\"rl-agent-e1-a2c\", pod=~\"product.*\", image!=\"\"}[2m])) /\nsum by (pod) (kube_pod_container_resource_requests{namespace=\"rl-agent-e1-a2c\", unit=\"byte\", pod=~\"product.*\"}) * 100)",
     "legendFormat": "memory-rl-agent-e1-a2c"
    },
    {
     "expr": "avg(sum by (pod) (rate(istio_requests_total{reporter=\"destination\", namespace=\"rl-agent-e1-ppo\", destination_workload=\"productcatalogservice\"}[1m])))",
     "legendFormat": "RPS-rl-agent-e1-ppo"
    },
    {
     "expr": "avg(sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"rl-agent-e1-ppo\", pod=~\"product.*\", image!=\"\"}[2m])) /\nsum by (pod) (kube_pod_container_resource_requests{namespace=\"rl-agent-e1-ppo\", unit=\"core\", pod=~\"product.*\"}) * 100)",
     "legendFormat": "CPU-rl-agent-e1-ppo"
    },
    {
     "expr": "(histogram_quantile(\n      0.95,\n      sum by (le) (\n        rate(\n          istio_request_duration_milliseconds_bucket{\n            reporter=\"destination\",\n            destination_service_namespace=\"rl-agent-e1-ppo\",\n            response_code=\"200\",\n            pod=~\"productcatalogservice-.*\"\n          }[1m]\n        )\n      )\n    )\n  )\n",
     "legendFormat": "p95-rl-agent-e1-ppo"
    },
    {
     "expr": "count(kube_pod_info{pod=~\"productcatalogservice-.*\", namespace=\"rl-agent-e1-ppo\"})",
     "legendFormat": "replicas-rl-agent-e1-ppo"
    },
    {
     "expr": "avg(sum by (pod) (rate(container_memory_usage_bytes{namespace=\"rl-agent-e1-ppo\", pod=~\"product.*\", image!=\"\"}[2m])) /\nsum by (pod) (kube_pod_container_resource_requests{namespace=\"rl-agent-e1-ppo\", unit=\"byte\", pod=~\"product.*\"}) * 100)",
     "legendFormat": "memory-rl-agent-e1-ppo"
    },
    {
     "expr": "avg(sum by (pod) (rate(istio_requests_total{reporter=\"destination\", namespace=\"rl-agent-e3-1\", destination_workload=\"productcatalogservice\"}[1m])))",
     "legendFormat": "RPS-rl-agent-e3-1"
    },
    {
     "expr": "avg(sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"rl-agent-e3-1\", pod=~\"product.*\", image!=\"\"}[2m])) /\nsum by (pod) (kube_pod_container_resource_requests{namespace=\"rl-agent-e3-1\", unit=\"core\", pod=~\"product.*\"}) * 100)",
     "legendFormat": "CPU-rl-agent-e3-1"
    },
    {
     "expr": "(histogram_quantile(\n      0.95,\n      sum by (le) (\n        rate(\n          istio_request_duration_milliseconds_bucket{\n            reporter=\"destination\",\n            destination_service_namespace=\"rl-agent-e3-1\",\n            response_code=\"200\",\n            pod=~\"productcatalogservice-.*\"\n          }[1m]\n        )\n      )\n    )\n  )\n",
     "legendFormat": "p95-rl-agent-e3-1"
    },
    {
     "expr": "count(kube_pod_info{pod=~\"productcatalogservice-.*\", namespace=\"rl-agent-e3-1\"})",
     "legendFormat": "replicas-rl-agent-e3-1"
    },
    {
     "expr": "avg(sum by (pod) (rate(container_memory_usage_bytes{namespace=\"rl-agent-e3-1\", pod=~\"product.*\", image!=\"\"}[2m])) /\nsum by (pod) (kube_pod_container_resource_requests{namespace=\"rl-agent-e3-1\", unit=\"byte\", pod=~\"product.*\"}) * 100)",
     "legendFormat": "memory-rl-agent-e3-1"
    },
    {
     "expr": "avg(sum by (pod) (rate(istio_requests_total{reporter=\"destination\", namespace=\"rl-agent-e3-2\", destination_workload=\"productcatalogservice\"}[1m])))",
     "legendFormat": "RPS-rl-agent-e3-2"
    },
    {
     "expr": "avg(sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"rl-agent-e3-2\", pod=~\"product.*\", image!=\"\"}[2m])) /\nsum by (pod) (kube_pod_container_resource_requests{namespace=\"rl-agent-e3-2\", unit=\"core\", pod=~\"product.*\"}) * 100)",
     "legendFormat": "CPU-rl-agent-e3-2"
    },
    {
     "expr": "(histogram_quantile(\n      0.95,\n      sum by (le) (\n        rate(\n          istio_request_duration_milliseconds_bucket{\n            reporter=\"destination\",\n            destination_service_namespace=\"rl-agent-e3-2\",\n            response_code=\"200\",\n            pod=~\"productcatalogservice-.*\"\n          }[1m]\n        )\n      )\n    )\n  )\n",
     "legendFormat": "p95-rl-agent-e3-2"
    },
    {
     "expr": "count(kube_pod_info{pod=~\"productcatalogservice-.*\", namespace=\"rl-agent-e3-2\"})",
     "legendFormat": "replicas-rl-agent-e3-2"
    },
    {
     "expr": "avg(sum by (pod) (rate(container_memory_usage_bytes{namespace=\"rl-agent-e3-2\", pod=~\"product.*\", image!=\"\"}[2m])) /\nsum by (pod) (kube_pod_container_resource_requests{namespace=\"rl-agent-e3-2\", unit=\"byte\", pod=~\"product.*\"}) * 100)",
     "legendFormat": "memory-rl-agent-e3-2"
    },
    {
     "expr": "avg(sum by (pod) (rate(istio_requests_total{reporter=\"destination\", namespace=\"rl-agent-e4-1\", destination_workload=\"productcatalogservice\"}[1m])))",
     "legendFormat": "RPS-rl-agent-e4-1"
    },
    {
     "expr": "avg(sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"rl-agent-e4-1\", pod=~\"product.*\", image!=\"\"}[2m])) /\nsum by (pod) (kube_pod_container_resource_requests{namespace=\"rl-agent-e4-1\", unit=\"core\", pod=~\"product.*\"}) * 100)",
     "legendFormat": "CPU-rl-agent-e4-1"
    },
    {
     "expr": "(histogram_quantile(\n      0.95,\n      sum by (le) (\n        rate(\n          istio_request_duration_milliseconds_bucket{\n            reporter=\"destination\",\n            destination_service_namespace=\"rl-agent-e4-1\",\n            response_code=\"200\",\n            pod=~\"productcatalogservice-.*\"\n          }[1m]\n        )\n      )\n    )\n  )\n",
     "legendFormat": "p95-rl-agent-e4-1"
    },
    {
     "expr": "count(kube_pod_info{pod=~\"productcatalogservice-.*\", namespace=\"rl-agent-e4-1\"})",
     "legendFormat": "replicas-rl-agent-e4-1"
    },
    {
     "expr": "avg(sum by (pod) (rate(container_memory_usage_bytes{namespace=\"rl-agent-e4-1\", pod=~\"product.*\", image!=\"\"}[2m])) /\nsum by (pod) (kube_pod_container_resource_requests{namespace=\"rl-agent-e4-1\", unit=\"byte\", pod=~\"product.*\"}) * 100)",
     "legendFormat": "memory-rl-agent-e4-1"
    },
    {
     "expr": "avg(sum by (pod) (rate(istio_requests_total{reporter=\"destination\", namespace=\"default\", destination_workload=\"productcatalogservice\"}[1m])))",
     "legendFormat": "RPS-default"
    },
    {
     "expr": "avg(sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"product.*\", image!=\"\"}[2m])) /\nsum by (pod) (kube_pod_container_resource_requests{namespace=\"default\", unit=\"core\", pod=~\"product.*\"}) * 100)",
     "legendFormat": "CPU-default"
    },
    {
     "expr": "(histogram_quantile(\n      0.95,\n      sum by (le) (\n        rate(\n          istio_request_duration_milliseconds_bucket{\n            reporter=\"destination\",\n            destination_service_namespace=\"default\",\n            response_code=\"200\",\n            pod=~\"productcatalogservice-.*\"\n          }[1m]\n        )\n      )\n    )\n  )\n",
     "legendFormat": "p95-default"
    },
    {
     "expr": "count(kube_pod_info{pod=~\"productcatalogservice-.*\", namespace=\"default\"})",
     "legendFormat": "replicas-default"
    },
    {
     "expr": "avg(sum by (pod) (rate(container_memory_usage_bytes{namespace=\"default\", pod=~\"product.*\", image!=\"\"}[2m])) /\nsum by (pod) (kube_pod_container_resource_requests{namespace=\"default\", unit=\"byte\", pod=~\"product.*\"}) * 100)",
     "legendFormat": "memory-default"
    },
    {
     "expr": "(sum(rate(istio_requests_total{reporter=\"destination\", namespace=\"testing\", destination_workload=\"productcatalogservice\"}[1m])))",
     "legendFormat": "dep_RPS-testing"
    },
    {
     "expr": "(sum(rate(istio_requests_total{reporter=\"destination\", namespace=\"default\", destination_workload=\"productcatalogservice\"}[1m])))",
     "legendFormat": "dep_RPS-default"
    },
    {
     "expr": "(sum(rate(istio_requests_total{reporter=\"destination\", namespace=\"rl-agent-e1-a2c\", destination_workload=\"productcatalogservice\"}[1m])))",
     "legendFormat": "dep_RPS-rl-agent-e1-a2c"
    },
    {
     "expr": "(sum(rate(istio_requests_total{reporter=\"destination\", namespace=\"rl-agent-e1-ppo\", destination_workload=\"productcatalogservice\"}[1m])))",
     "legendFormat": "dep_RPS-rl-agent-e1-ppo"
    },
    {
     "expr": "(sum(rate(istio_requests_total{reporter=\"destination\", namespace=\"rl-agent-e3-1\", destination_workload=\"productcatalogservice\"}[1m])))",
     "legendFormat": "dep_RPS-rl-agent-e3-1"
    },
    {
     "expr": "(sum(rate(istio_requests_total{reporter=\"destination\", namespace=\"rl-agent-e3-2\", destination_workload=\"productcatalogservice\"}[1m])))",
     "legendFormat": "dep_RPS-rl-agent-e3-2"
    },
    {
     "expr": "(sum(rate(istio_requests_total{reporter=\"destination\", namespace=\"rl-agent-e4-1\", destination_workload=\"productcatalogservice\"}[1m])))",
     "legendFormat": "dep_RPS-rl-agent-e4-1"
    }
   ]
  }
 ]
}