apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: tbi-gcr-admin-role
  namespace: master-thesis-hpa
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: "projects/master-thesis-hpa"
  bindings:
    - role: roles/storage.admin
      condition:
        expression: 'resource.name.startsWith("projects/_/buckets/artifacts.master-thesis-hpa.appspot.com") || resource.name.startsWith("projects/_/buckets/asia.artifacts.master-thesis-hpa.appspot.com") || resource.name.startsWith("projects/_/buckets/eu.artifacts.master-thesis-hpa.appspot.com") || resource.name.startsWith("projects/_/buckets/us.artifacts.master-thesis-hpa.appspot.com")'
        title: "Only on GCR"
        description: "GCR push access for the TBI SA to the project master-thesis-hpa"
      members:
        - member: serviceAccount:placeholder # {"$kpt-set":"build-identity.service-account-binding"}